apiVersion: apps/v1
kind: Deployment
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "kubevirt-operator.fullname" . }}
  # because we need to keep it as same as all-in-one YAML from upstream.
  name: virt-operator
  labels:
{{ include "kubevirt-operator.labels" . | indent 4 }}
    kubevirt.io: virt-operator
    app.kubernetes.io/name: virt-operator
    app.kubernetes.io/component: operator
spec:
  selector:
    matchLabels:
{{ include "kubevirt-operator.immutableLabels" . | indent 6 }}
      app.kubernetes.io/name: virt-operator
      app.kubernetes.io/component: operator
      kubevirt.io: virt-operator
{{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
{{- end }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
{{ include "kubevirt-operator.labels" . | indent 8 }}
        app.kubernetes.io/name: virt-operator
        app.kubernetes.io/component: operator
        kubevirt.io: virt-operator
        prometheus.kubevirt.io: ""
    spec:
      priorityClassName: kubevirt-cluster-critical
      serviceAccountName: kubevirt-operator
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: kubevirt.io
                      operator: In
                      values:
                        - virt-operator
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: virt-operator
          image: {{ .Values.containers.operator.image.repository }}:{{ .Values.containers.operator.image.tag }}
          imagePullPolicy: {{ .Values.containers.operator.image.imagePullPolicy }}
{{- if .Values.containers.operator.command }}
          command:
{{ toYaml .Values.containers.operator.command | indent 12 }}
{{- end }}
{{- if .Values.containers.operator.args }}
          args:
{{ toYaml .Values.containers.operator.args | indent 12 }}
{{- end }}
          env:
{{- if .Values.containers.operator.env }}
{{ toYaml .Values.containers.operator.env | indent 12 }}
{{- end }}
            - name: OPERATOR_IMAGE
              value: {{ .Values.containers.operator.image.repository }}:{{ .Values.containers.operator.image.tag }}
          ports:
            - containerPort: 8443
              name: metrics
              protocol: TCP
            - containerPort: 8444
              name: webhooks
              protocol: TCP
{{- if .Values.containers.operator.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.containers.operator.livenessProbe | indent 12 }}
{{- end }}
{{- if .Values.containers.operator.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.containers.operator.readinessProbe | indent 12 }}
{{- end }}
{{- if .Values.containers.operator.resources }}
          resources:
{{ toYaml .Values.containers.operator.resources | indent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/virt-operator/certificates
              name: kubevirt-operator-certs
              readOnly: true
            - mountPath: /profile-data
              name: profile-data
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
      volumes:
        - name: kubevirt-operator-certs
          secret:
            optional: true
            secretName: {{ .Values.containers.operator.certificates.admissionWebhook.secretName }}
        - emptyDir: {}
          name: profile-data
