apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "kubevirt-operator.fullname" . }}
  # because we need to keep it as same as all-in-one YAML from upstream.
  name: kubevirt-operator-rolebinding
  labels:
{{ include "kubevirt-operator.labels" . | indent 4 }}
    kubevirt.io: ""
    app.kubernetes.io/name: virt-operator
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "kubevirt-operator.fullname" . }}
  # because we need to keep it as same as all-in-one YAML from upstream.
  name: kubevirt-operator
subjects:
  - kind: ServiceAccount
    # NB(thxCode): name should not be customized as below:
    # name: {{ template "kubevirt-operator.fullname" . }}
    # because we need to keep it as same as all-in-one YAML from upstream.
    name: kubevirt-operator
    namespace: {{ .Release.Namespace }}
