apiVersion: v1
kind: ServiceAccount
metadata:
  # NB(thxCode): name cannot be customized as below:
  # name: {{ template "kubevirt-operator.fullname" . }}
  # because the installation strategy dump action needs this ServiceAccount.
  name: kubevirt-operator
  labels:
{{ include "kubevirt-operator.labels" . | indent 4 }}
    kubevirt.io: ""
    app.kubernetes.io/name: virt-operator
    app.kubernetes.io/component: operator
