apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "multus.name" . }}-ds-amd64
  namespace: kube-system
  labels:
  {{- include "multus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "multus.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
    {{- include "multus.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ include "multus.name" . }}
      containers:
        - name: kube-multus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint.sh"]
          args:
            - "--multus-conf-file=auto"
            - "--cni-version=0.3.1"
          {{- with .Values.args }}
          {{- range . }}
            - {{ . | quote }}
          {{- end }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni
              mountPath: /host/etc/cni/net.d
            - name: cnibin
              mountPath: /host/opt/cni/bin
            - name: multus-cfg
              mountPath: /tmp/multus-conf
      volumes:
        - name: cni
          hostPath:
            path: {{ .Values.hostPath.cniConfDir }}
        - name: cnibin
          hostPath:
            path: {{ .Values.hostPath.cniBinDir }}
        - name: multus-cfg
          configMap:
            name: {{ include "multus.name" . }}-cni-config
            items:
              - key: cni-conf.json
                path: 70-multus.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
