
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: virtualmachinetemplates.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: VirtualMachineTemplate
    listKind: VirtualMachineTemplateList
    plural: virtualmachinetemplates
    shortNames:
    - vmtemplate
    - vmtemplates
    singular: virtualmachinetemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.defaultVersionId
      name: VERSION_ID
      type: string
    - jsonPath: .spec.description
      name: DESCRIPTION
      priority: 10
      type: string
    - jsonPath: .status.defaultVersion
      name: VERSION_DEFAULT
      priority: 8
      type: integer
    - jsonPath: .status.latestVersion
      name: VERSION_LATEST
      priority: 8
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              defaultVersionId:
                type: string
              description:
                type: string
            type: object
          status:
            properties:
              defaultVersion:
                type: integer
              latestVersion:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
