pull_request_rules:
- name: Automatically open v1.6 backport PR
  conditions:
    - base=master
    - label="pr-backport-to/v1.6"
  actions:
    backport:
      branches:
        - v1.6
      assignees:
        - "{{ author }}"

- name: Automatically open v1.5 backport PR
  conditions:
    - base=master
    - label="pr-backport-to/v1.5"
  actions:
    backport:
      branches:
        - v1.5
      assignees:
        - "{{ author }}"

- name: Automatically open v1.4 backport PR
  conditions:
    - base=master
    - label="pr-backport-to/v1.4"
  actions:
    backport:
      branches:
        - v1.4
      assignees:
        - "{{ author }}"

- name: Automatically merge Renovate PRs
  conditions:
  - check-success="Build binaries (x64)"
  - check-success="Build binaries (arm64)"
  - author = renovate[bot]
  - -conflict
  actions:
    merge:
      method: rebase

- name: Automatically merge Backport PRs
  conditions:
  - check-success="Build binaries (x64)"
  - check-success="Build binaries (arm64)"
  - author = mergify[bot]
  - -conflict
  actions:
    merge:
      method: rebase

- name: Automatically approve Renovate PRs
  conditions:
  - check-success="Build binaries (x64)"
  - check-success="Build binaries (arm64)"
  - author = renovate[bot]
  - -conflict
  actions:
    review:
      type: APPROVE

# Mergify can't approve its own PRs, so we need to use a bot account
- name: Automatically approve Backport PRs
  conditions:
  - check-success="Build binaries (x64)"
  - check-success="Build binaries (arm64)"
  - author = mergify[bot]
  - -conflict
  actions:
    review:
      type: APPROVE
      bot_account: harvesterhci-io-github-bot

- name: Ask to resolve conflict
  conditions:
  - conflict
  actions:
    comment:
      message: This pull request is now in conflict. Could you fix it @{{author}}? 🙏
