pull_request_rules:
  - name: Automatically merge Backport PRs
    conditions:
      - check-success="calling-build-factory / Build binaries (x64)"
      - check-success="calling-build-factory / Build binaries (arm64)"
      - author = mergify[bot]
      - -conflict
    actions:
      merge:
        method: squash

  - name: Automatically approve Renovate PRs
    conditions:
      - check-success="calling-build-factory / Build binaries (x64)"
      - check-success="calling-build-factory / Build binaries (arm64)"
      - author = renovate[bot]
      - -conflict
    actions:
      review:
        type: APPROVE
        bot_account: harvesterhci-io-github-bot

  # Mergify can't approve its own PRs, so we need to use a bot account
  - name: Automatically approve Backport PRs
    conditions:
      - check-success="calling-build-factory / Build binaries (x64)"
      - check-success="calling-build-factory / Build binaries (arm64)"
      - author = mergify[bot]
      - -conflict
    actions:
      review:
        type: APPROVE
        bot_account: harvesterhci-io-github-bot

  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict. Could you fix it @{{author}}? 🙏
