---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/vm"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/vm"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/vm"
    tag: ${DRONE_BRANCH}-head-arm64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/vm"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-master
  image: plugins/docker
  settings:
    build_args:
    - ARCH=arm
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/vm"
    tag: ${DRONE_BRANCH}-head-arm
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/vm"
    tag: "${DRONE_TAG}-arm"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-master
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm
    target: "rancher/vm:${DRONE_BRANCH}"
    template: "rancher/vm:${DRONE_BRANCH}-head-ARCH"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/v*"
    event:
    - push

- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
    target: "rancher/vm:${DRONE_TAG}"
    template: "rancher/vm:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- amd64
- arm64
- arm
