---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*
    event:
      - tag

- name: build
  image: rancher/dapper:v0.5.8
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: stage-binaries
  image: rancher/dapper:v0.5.8
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - push
    - tag

- name: docker-publish-branch
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/harvester"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/v*"
    event:
    - push

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/harvester"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish-webhook-branch
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile.webhook
    password:
      from_secret: docker_password
    repo: "rancher/harvester-webhook"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/v*"
    event:
    - push

- name: docker-publish-webhook
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - "VERSION=${DRONE_TAG}"
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile.webhook
    password:
      from_secret: docker_password
    repo: "rancher/harvester-webhook"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag


- name: docker-publish-upgrade-branch
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}-head
    context: package/upgrade
    custom_dns: 1.1.1.1
    dockerfile: package/upgrade/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/harvester-upgrade"
    tag: ${DRONE_BRANCH}-head-amd64
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/v*"
    event:
    - push

- name: docker-publish-upgrade
  image: plugins/docker
  settings:
    build_args:
    - ARCH=amd64
    - "VERSION=${DRONE_TAG}"
    context: package/upgrade
    custom_dns: 1.1.1.1
    dockerfile: package/upgrade/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/harvester-upgrade"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

trigger:
  branch:
    exclude:
    - mergify/**

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest-branch
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "rancher/harvester:${DRONE_BRANCH}-head"
    template: "rancher/harvester:${DRONE_BRANCH}-head-ARCH"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/v*"
    event:
    - push

- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
    target: "rancher/harvester:${DRONE_TAG}"
    template: "rancher/harvester:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: manifest-webhook-branch
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "rancher/harvester-webhook:${DRONE_BRANCH}-head"
    template: "rancher/harvester-webhook:${DRONE_BRANCH}-head-ARCH"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/v*"
    event:
    - push

- name: manifest-webhook
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
    target: "rancher/harvester-webhook:${DRONE_TAG}"
    template: "rancher/harvester-webhook:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: manifest-upgrade-branch
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
    - linux/amd64
    target: "rancher/harvester-upgrade:${DRONE_BRANCH}-head"
    template: "rancher/harvester-upgrade:${DRONE_BRANCH}-head-ARCH"
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/v*"
    event:
    - push

- name: manifest-upgrade
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
    target: "rancher/harvester-upgrade:${DRONE_TAG}"
    template: "rancher/harvester-upgrade:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

trigger:
  branch:
    exclude:
    - mergify/**

depends_on:
- amd64

---
kind: pipeline
name: build-iso

platform:
  os: linux
  arch: amd64

steps:
- name: fetch
  image: alpine/git
  commands:
  - git fetch --tags
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
      - refs/tags/*
    event:
      - tag

- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper build-iso
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
    - drone-publish.rancher.io

- name: upload_iso_release
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "public,no-cache,proxy-revalidate"
    source: dist/artifacts
    target: releases.rancher.com/harvester/${DRONE_TAG}
    token:
      from_secret: google_auth_key
  when:
    instance:
      - drone-publish.rancher.io
    event:
      - tag

- name: upload_iso_branch
  image: plugins/gcs
  settings:
    acl:
      - allUsers:READER
    cache_control: "public,no-cache,proxy-revalidate"
    source: dist/artifacts
    target: releases.rancher.com/harvester/${DRONE_BRANCH}
    token:
      from_secret: google_auth_key
  when:
    instance:
      - drone-publish.rancher.io
    event:
      - push

- name: upload_kernel_initrd_releases
  image: plugins/github-release
  settings:
    prerelease: true
    draft: true
    checksum:
      - sha256
    files:
    - "dist/artifacts/harvester*initrd-amd64"
    - "dist/artifacts/harvester*vmlinuz-amd64"
    api_key:
      from_secret: github_token
  when:
    instance:
      - drone-publish.rancher.io
    event:
      - tag

trigger:
  event:
    - tag
    - push
  ref:
    - "refs/heads/master"
    - "refs/heads/v*"
    - "refs/tags/*"

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

depends_on:
- manifest
