{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "logging-operator.fullname" . }}
  namespace: {{ include "logging-operator.namespace" . }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
{{- end }}
