apiVersion: v1
kind: Service
metadata:
  name: {{ include "logging-operator.fullname" . }}
  namespace: {{ include "logging-operator.namespace" . }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  {{- with  .Values.http.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "logging-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
