apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "logging-admin"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "logging.banzaicloud.io"
    resources:
      - flows
      - outputs
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "logging-view"
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - "logging.banzaicloud.io"
    resources:
      - flows
      - outputs
      - clusterflows
      - clusteroutputs
    verbs:
      - get
      - list
      - watch
