# NB(thxCode): the api version controls by the app version specification of Chart.yaml.
apiVersion: {{ printf "cdi.kubevirt.io/%s" .Chart.AppVersion }}
kind: CDI
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "cdi.fullname" . }}
  # because multiple CDI resources are useless,
  # only the first instance will be deployed.
  name: cdi
  labels:
{{ include "cdi.labels" . | indent 4 }}
    app.kubernetes.io/name: cdi
    app.kubernetes.io/component: metadata
spec:
{{- if .Values.spec }}
{{ toYaml .Values.spec | indent 2 }}
{{- end }}
