{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ga-operator.serviceAccountName" . }}
  labels:
{{ include "ga-operator.labels" . | indent 4 }}
{{- end -}}

