{{- define "logging-operator.logging.gke" -}}
{{- $logPath := "/var/log/kube-proxy.log" -}}
metadata:
  name: {{ .Release.Name }}-gke
spec:
  fluentbit:
    disableKubernetesFilter: true
    extraVolumeMounts:
      - source: {{ $logPath }}
        destination: {{ $logPath }}
        readOnly: true
    inputTail:
      Tag: "gke"
      Path: {{ $logPath }}
{{- end -}}
{{- if .Values.additionalLoggingSources.gke.enabled }}
{{- include "logging-operator.logging" (list . "logging-operator.logging.gke") -}}
{{- end }}
