apiVersion: v1
kind: Service
metadata:
  name: {{ include "snapshot-validation-webhook.fullname" . }}
  namespace: {{ include "snapshot-validation-webhook.namespace" . }}
  labels: {{ include "snapshot-validation-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 443 }}
      targetPort: https
      protocol: TCP
      name: https
  selector: {{ include "snapshot-validation-webhook.selectorLabels" . | nindent 4 }}