---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvester-network-controller.labels" . | nindent 4 }}
  name: {{ include "harvester-network-controller.name" . }}-manager
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      {{- include "harvester-network-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "harvester-network-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "harvester-network-controller.name" . }}
      containers:
        - name: network-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - harvester-network-controller
          args:
            - manager
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- with .Values.manager.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.manager.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
