# This file is only used in v1.0.3 -> v1.1.0 upgrade path
# Please keep syncing with harvester, harvester-installer v1.1.0 version
#   harvester/harvester-installer/pkg/config/templates/rancherd-14-logging-crd.yaml
#   harvester/harvester-installer/pkg/config/templates/rancherd-15-logging.yaml
# Notice the slight difference in format between chart file and normal kubectl accepted file
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: EventTailer
metadata:
  name: harvester-default
  namespace: cattle-logging-system
spec:
  controlNamespace: cattle-logging-system
  # https://banzaicloud.com/docs/one-eye/logging-operator/configuration/extensions/kubernetes-event-tailer/
  # workloadOverrides *types.PodSpecBase
  workloadOverrides:
    containers:
    - image: banzaicloud/eventrouter:v0.1.0
      name: event-tailer
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 20Mi
