# This file is only used in v1.0.3 -> v1.1.0 upgrade path
# Please keep syncing with harvester, harvester-installer v1.1.0 version
#   harvester/harvester-installer/pkg/config/templates/rancherd-14-logging-crd.yaml
#   harvester/harvester-installer/pkg/config/templates/rancherd-15-logging.yaml
# Notice the slight difference in format between chart file and normal kubectl accepted file
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-logging-system
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: rancher-logging-crd
  namespace: fleet-local
spec:
  chart: rancher-logging-crd
  releaseName: rancher-logging-crd
  version: "100.1.3+up3.17.7"
  defaultNamespace: cattle-logging-system
  repoName: harvester-charts
  targets:
  - clusterName: local
    clusterSelector:
      matchExpressions:
      - key: provisioning.cattle.io/unmanaged-system-agent
        operator: DoesNotExist
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: rancher-logging
  namespace: fleet-local
spec:
  chart: rancher-logging
  releaseName: rancher-logging
  version: "100.1.3+up3.17.7"
  defaultNamespace: cattle-logging-system
  repoName: harvester-charts
  targets:
  - clusterName: local
    clusterSelector:
      matchExpressions:
      - key: provisioning.cattle.io/unmanaged-system-agent
        operator: DoesNotExist
  values:
    images:
      fluentbit:
        tag: 1.9.5 # replace the default 1.9.3, which has bug in systemd log
      fluentbit_debug:
        tag: 1.9.5-debug
    systemdLogPath: /var/log/journal
    disablePvc: true
    additionalLoggingSources:
      rke2:
        enabled: true
      kubeAudit:
        enabled: true
        auditFilename: "audit.log"
        pathPrefix: "/var/lib/rancher/rke2/server/logs/"
        loggingRef: "harvester-kube-audit-log-ref"
        fluentbit:
          logTag: kube-audit
          tolerations:
          - key: node-role.kubernetes.io/controlplane
            value: "true"
            effect: NoSchedule
          - key: node-role.kubernetes.io/etcd
            value: "true"
            effect: NoExecute
    fluentd:
      resources:
        limits:
          cpu: 1000m
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 200Mi
    fluentbit:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
