resources:
- deployment.yaml
- rbac.yaml
- service.yaml

# Adds namespace to all resources.
namespace: kube-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: rancher-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/name: "rancher-vm"
  app.kubernetes.io/version: "master"

## Images to overwrite the default images.
images:
- name: rancher/vm
  newName: rancher/vm
  newTag: master
