apiVersion: v1
kind: Service
metadata:
  name: vm
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 8443
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/component: server
