###########################################################################
###########################################################################
##                     Default values for KubeVirt CR                    ##
###########################################################################
###########################################################################

## Provide a name in place of labels.
##
nameOverride: ""

## Provide a name to substitute for the full names of resources.
##
fullnameOverride: ""

## Specify the specification of KubeVirt resource.
##
spec:

  ## Specify the image tag of KubeVirt bundle components,
  ## defaults to the same tag as the operator image.
  ##
  # imageTag: ""

  ## Specify the image registry of KubeVirt bundle components,
  ## defaults to the same registry as the operator image.
  ##
  # imageRegistry: ""

  ## Specify the image pull policy of KubeVirt bundle components,
  ## defaults to "IfNotPresent".
  ##
  # imagePullPolicy: "IfNotPresent"

  ## Specify the namespace Prometheus is deployed in OpenShift,
  ## defaults to "openshift-monitor".
  ##
  # monitorNamespace: "openshift-monitor"

  ## Specify the name of the Prometheus service account that needs read-access to KubeVirt endpoints in OpenShift,
  ## defaults to "prometheus-k8s".
  # monitorAccount: "prometheus-k8s"

  ## Specify the uninstall strategy of KubeVirt resource,
  ## select from [RemoveWorkloads, BlockUninstallIfWorkloadsExist],
  ## defaults to "RemoveWorkloads".
  ## -- If specifies to BlockUninstallIfWorkloadsExist, we cannot drop KubeVirt CRD directly, we need to change this field to blank or RemoveWorkloads.
  ##
  # uninstallStrategy: "RemoveWorkloads"

  ## Specify the strategy of KubeVrit bundle components certificate rotation.
  ##
  # certificateRotateStrategy:

    ## Specify the configuration of self signed certificate.
    ##
    # selfSigned:

      ## Specify the interval of CA rotation,
      ## defaults to "168h", 7d.
      ##
      # caRotateInterval: "168h"

      ## Specify the interval of Certificate rotation,
      ## defaults to "24h", 1d.
      ##
      # certRotateInterval: "24h"

      ## Specify the interval of CA overlap,
      ## defaults to "24h", 1d.
      # caOverlapInterval: "24h"

  customizeComponents:
    patches:
      - patch: '{"webhooks":[{"name":"kubevirt-validator.kubevirt.io","failurePolicy":"Ignore"},{"name":"kubevirt-update-validator.kubevirt.io","failurePolicy":"Ignore"}]}'
        resourceName: virt-operator-validator
        resourceType: ValidatingWebhookConfiguration
        type: strategic

  ## Specify the default configuration of KubeVirt virtual machine.
  ##
  configuration:

    ## Specify the directory that contains the EFI roms,
    ## this argument will be passed to "virt-launcher" as "--ovmf-path",
    ## defaults to "/usr/share/OVMF".
    ##
    # ovmfPath: "/usr/share/OVMF"

    ## Specify the SELinux type, this argument will fill into `spec.securityContext.selinuxOptions.type` of the generated Pod for "virt-launcher",
    ## and also fill into `spec.containers[?(.name!=compute)].securityContext.selinuxOptions.type` and `spec.containers[?(.name!=compute)].securityContext.selinuxOptions.level=s0`.
    ##
    # selinuxLauncherType: ""

    ## Specify the version regex of guest agent, which is used for processing the Condition(AgentVersionNotSupported) of VirtualMachineInstance,
    ## defaults to "[3.*, 4.*]".
    #
    # supportedGuestAgentVersions:
      # - "3.*"
      # - "4.*"

    ## Specify the default CPU model of VirtualMachineInstance, selects from https://github.com/libvirt/libvirt/tree/master/src/cpu_map,
    ## defaults to "host-model".
    ##
    # cpuModel: "host-model"

    ## Specify the default CPU request of VirtualMachineInstance(`spec.domain.requests.cpu`),
    ## defaults to "100m"
    ##
    # cpuRequest: "100m"

    ## Specify the machine type regex for validating the emulation of VirtualMachineInstance,
    ## defaults to discover automatically, "pseries*" if arch is ppc64le, otherwise "q35*,pc-q35*".
    ##
    # emulatedMachines: []

    ## Specify the machine type for filling VirtualMachineInstance(`spec.domain.machine.type`),
    ## defaults to discover automatically, "pseries" if arch is ppc64le, otherwise "q35".
    ##
    # machineType: ""

    ## Specify the virtual machine image pull policy of `virt-launcher` Pod,
    ## defaults to "IfNotPresent".
    ##
    # imagePullPolicy: "IfNotPresent"

    ## Specify the developer configuration of KubeVirt.
    ##
    developerConfiguration:

      ## Specify whether an optional feature is enabled at the global level.
      ## Select many from [
      ##    CPUManager, ExperimentalIgnitionSupport, LiveMigration,
      ##    SRIOVLiveMigration, CPUNodeDiscovery, HypervStrictCheck,
      ##    Sidecar, GPU, HostDevices, Snapshot, HotplugVolumes,
      ##    HostDisk, ExperimentalVirtiofsSupport, Macvtap, DownwardMetrics
      ## ].
      ## Ref to: https://github.com/kubevirt/kubevirt/blob/7c7a2f4ace9ce3a88b164d4d282db55f08b6dc5e/pkg/virt-config/feature-gates.go#L26-L44.
      ##
      # featureGates: ["LiveMigration", "HotplugVolumes"]

      ## Specify the toleration in percent when PVs' available space is smaller than requested,
      ## this argument will be passed to "virt-launcher" as "--less-pvc-space-toleration",
      ## defaults to "10" percent.
      ##
      # pvcTolerateLessSpaceUpToPercont: "10"

      ## Specify the memory overcommit in percent,
      ## which will effect VirtualMachineInstance(`spec.domain.resources.memory`),
      ## defaults to "100" percent, which means 100% to overcommit the memory.
      ##
      # memoryOvercommit: "100"

      ## Specify the selector of VirtualMachineInstance(`spec.nodeSelector`), it can override the same key defined in origin.
      ## -- When enabling "CPUNodeDiscovery" feature, `feature.node.kubernetes.io/cpu-model-<model-specified-in-crd>=true` will attach to here if `spec.domain.cpu.model` is not blank, except "host-model" and "host-passthourgh".
      ##    And then, `feature.node.kubernetes.io/cpu-feature-<feature-name-specified-in-crd>=true` if `spec.domain.cpu.features` is not empty and the policy of feature is "require".
      ## -- When enabling "HypervStrictCheck" feature, `feature.node.kubernetes.io/kvm-info-cap-hyperv-<feature-label-name-specified-in-crd>=true` will attach to here if `spec.domain.cpu.hyperv` is not empty.
      ## -- `kubevirt.io/schedulable=true` must attach to here.
      ##
      # nodeSelector: {}

      ## Specify if uses eumlation,
      ## this argument will be passed to "virt-launcher" as "--use-eumlation",
      ## defaults to "false".
      ## -- `devices.kubevirt.io/kvm=1` will attach to `resources.limits` if here is "false".
      ##
      # useEmulation: "false"

    ## Specify the migration configuration of KubeVirt.
    ##
    # migrations:

      ## Specify if allows to converge automatically,
      ## defaults to "false"
      ##
      # allowAutoConverge: "false"

      ## Specify the bandwidth per migration,
      ## defaults to "64Mi"
      ##
      # bandwidthPerMigration: "64Mi"

      ## Specify the timeout for completing each GB migration,
      ## defaults to "800".
      ##
      # completionTimeoutPerGiB: "800"

      ## Specify the label of node,
      ## defaults to "kubevirt.io/drain".
      ##
      # nodeDrainTaintKey: "kubevirt.io/drain"

      ## Specify the amount of outbound migrations of parallels per node,
      ## defaults to "2".
      ##
      # parallelOutboundMigrationsPerNode: "2"

      ## Specify the amount of migrations of parallels per cluster,
      ## defaults to "5".
      ##
      # parallelMigrationsPerCluster: "5"

      ## Specify the timeout of progress,
      ## defaults to "150".
      ##
      # progressTimeout: "150"

      ## Specify if overrides unsafe migration,
      ## defaults to "false".
      ##
      # unsafeMigrationOverride: "false"

    ## Specify the network configuration of VirtualMachineInstance.
    ##
    # network:

      ## Specify the default network interface of VirtualMachineInstance(`spec.domain.devices.interfaces[?(.name="default")]`),
      ## defaults to "bridge".
      ##
      # defaultNetworkInterface: "bridge"

      ## Specify to permit slirp interface,
      ## defaults to "false".
      ## -- If the `defaultNetworkInterface` is "slirp", here must specify to "true".
      ##
      # permitSlirpInterface: "false"

      ## Specify to permit bridge interface,
      ## defaults to "true".
      ## -- If the `defaultNetworkInterface` is "bridge", here must specify to "true".
      ##
      # permitBridgeInterfaceOnPodNetwork: "true"

    ## Specify the SMBIOS which should pass to "libvirt".
    ##
    # smbios:

      ## Specify the manufacturer,
      ## defaults to "KubeVirt".
      ##
      # manufacturer: "KubVirt"

      ## Specify the product,
      ## defaults to "None".
      ##
      # product: "None"

      ## Specify the version.
      ##
      # version: ""

      ## Specify the SKU.
      ##
      # sku: ""

      ## Specify the family,
      ## defaults to "KubeVirt".
      ##
      # family: "KubeVirt"
