apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: harvester-seeder
  namespace: harvester-system
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "0.1.0-rc3"
  chart: harvester-seeder
  enabled: false
  valuesContent: |
    image:
      tag: v0.1.0-rc3
    fullnameOverride: harvester-seeder