apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: rancher-logging
  namespace: cattle-logging-system
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "102.0.0+up3.17.10"
  chart: rancher-logging
  enabled: false
  valuesContent: |
    images:
      fluentbit:
        tag: 1.9.5 # replace the default 1.9.3, which has bug in systemd log
      fluentbit_debug:
        tag: 1.9.5-debug
    systemdLogPath: /var/log/journal
    disablePvc: true
    additionalLoggingSources:
      rke2:
        enabled: true
      kubeAudit:
        enabled: true
        auditFilename: "audit.log"
        pathPrefix: "/var/lib/rancher/rke2/server/logs/"
        loggingRef: "harvester-kube-audit-log-ref"
        fluentbit:
          logTag: kube-audit
          tolerations:
          - key: node-role.kubernetes.io/controlplane
            value: "true"
            effect: NoSchedule
          - key: node-role.kubernetes.io/etcd
            value: "true"
            effect: NoExecute
    fluentd:
      resources:
        limits:
          cpu: 1000m
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 200Mi
    fluentbit:
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
    eventTailer:
      name: harvester-default
      namespace: cattle-logging-system
      controlNamespace: cattle-logging-system
      workloadOverrides:
        containers:
        - image: rancher/harvester-eventrouter:v0.1.1
          name: event-tailer
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 20Mi
