apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: nvidia-driver-toolkit
  namespace: harvester-system
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "0.1.1"
  chart: nvidia-driver-runtime
  enabled: false
  valuesContent: |
    image:
      tag: v1.3-20240531
      repo: rancher/harvester-nvidia-driver-toolkit
    driverLocation:  "HTTPENDPOINT/NVIDIA-Linux-x86_64-vgpu-kvm.run"
    fullnameOverride: nvidia-driver-runtime
