apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: pcidevices-controller
  namespace: harvester-system
  labels:
    addon.harvesterhci.io/experimental: "true"
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "0.2.1-rc3"
  chart: harvester-pcidevices-controller
  enabled: false
  valuesContent: |
    image:
      tag: v0.2.1-rc4
    fullnameOverride: harvester-pcidevices-controller