apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: pcidevices-controller
  namespace: harvester-system
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "0.3.3"
  chart: harvester-pcidevices-controller
  enabled: false
  valuesContent: |
    image:
      tag: v0.3.3
    fullnameOverride: harvester-pcidevices-controller
