name: Feature request
description: Suggest a feature or enhancement
title: "[FEATURE] "
labels: [ "kind/feature", "require/hep", "require/doc" ]
assignees:
-
body:
- type: markdown
  attributes:
    value: |
      Thanks for stopping by to let us know something could be better!
      
      For general questions or discussions, please use the [Discussions](https://github.com/harvester/harvester/discussions) tab.

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe (👍 if you like this request)
    description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: false

- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional context
    placeholder: Add any other context or screenshots about the feature request here.
  validations:
    required: false
