name: Task request (component update)
description: Create a component update task targeting a specific Harvester release
title: "[TASK] Component updates for Harvester v"
labels: [ "kind/task", "area/build-package" ]
assignees:
-
body:
- type: textarea
  attributes:
    label: Component update request
    description: |
      List the dependent components that need to be updated for a specific Harvester release.

      Please note that for different Harvester releases, the component update strategies are different:
      - For feature or minor releases, the minor version of the component should be updated.
      - For patch releases, only the patch version of the component should be updated.
      - For built-in components/add-ons, the version should be aligned with the Harvester version.
    value: |
      Components to be updated for Harvester version vx.y.z:
      - [ ] Embedded Rancher vx.y.z @FrankYang0529
      - [ ] RKE2 vx.y.z @FrankYang0529
      - [ ] Longhorn vx.y.z @Vicente-Cheng
      - [ ] KubeVirt vx.y.z @Vicente-Cheng
      - [ ] Built-in components/add-ons (e.g., Network Controller, Node Disk Manager, VM Import Controller, etc.) vx.y.z @harvester/dev
      - ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: Please add any other context about the task here.
  validations:
    required: false
