name: Infra request
description: Create an Infra task
title: "[INFRA] "
type: "Task"
labels: [ "kind/task", "area/infra" ]
assignees:
-
body:
- type: textarea
  attributes:
    label: Task request
    description: A clear and concise description of what the task is.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: Please add any other context about the problem here.
  validations:
    required: false
