###########################################################################
###########################################################################
##                   Default values for KubeVirt Operator                ##
###########################################################################
###########################################################################

## Provide a name in place of labels.
##
nameOverride: ""

## Provide a name to substitute for the full names of resources.
##
fullnameOverride: ""

## Specify the replicas of workload.
##
replicas: 1

## Specify the security context of workload.
##
securityContext:
  runAsNonRoot: true

## Specify the node selector of workload.
##
nodeSelector: {}

## Specify the tolerations of workload.
##
tolerations: []
#  - key: CriticalAddonsOnly
#    operator: Exists

## Specify the update strategy of workload.
##
strategy:
  type: RollingUpdate

## Specify the parameter of containers.
##
containers:

  ## Specify the parameter of kubevirt-operator container.
  ##
  operator:

    ## Specify the image.
    ##
    image:

      ## Specify the pull policy of image.
      ##
      imagePullPolicy: IfNotPresent

      ## Specify the repository of image.
      ##
      repository: quay.io/kubevirt/virt-operator

      ## Specify the tag of image.
      ##
      tag: v0.40.0

    ## Specify the command.
    ##
    command:
      - virt-operator
      - --port
      - "8443"
      - -v
      - "2"

    ## Specify the args.
    ##
    args: []

    ## Specify the env.
    ##
    env: []
    #  - name: OPERATOR_IMAGE
    #    value: xxx

    ## Specify the liveness probe.
    ##
    livenessProbe:
      httpGet:
        path: /metrics
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10

    ## Specify the readiness probe.
    ##
    readinessProbe:
      httpGet:
        path: /metrics
        port: 8443
        scheme: HTTPS
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 10

    ## Specify the resources.
    ##
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    ## Specify the certificate.
    ##
    certificates:

      ## For admission webhook.
      ##
      admissionWebhook:

        ## Specify the name of the same namespace existing Secret instance,
        ## which stored the admission webhook certificate of KubeVirt Operator.
        ##
        secretName: "kubevirt-operator-certs"
        ## TODO should we support to inject certificate from values?
