cdi:
  config:
    featureGates:
      - HonorWaitForFirstConsumer
  imagePullPolicy: "IfNotPresent"
  infra:
    nodeSelector:
      kubernetes.io/os: linux
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
  uninstallStrategy: ""
  workload:
    nodeSelector:
      kubernetes.io/os: linux

hookRestartPolicy: OnFailure
hookSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

containers:
  hook:
    image:
      repository: rancher/kuberlr-kubectl
      tag: v7.0.3
