---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: schedulevmbackups.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: ScheduleVMBackup
    listKind: ScheduleVMBackupList
    plural: schedulevmbackups
    shortNames:
    - svmbackup
    - svmbackups
    singular: schedulevmbackup
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.cron
      name: Cron
      type: string
    - jsonPath: .spec.retain
      name: Retain
      type: integer
    - jsonPath: .spec.maxFailure
      name: MaxFailure
      type: integer
    - jsonPath: .spec.suspend
      name: SpecSuspend
      type: boolean
    - jsonPath: .spec.vmbackup.source.name
      name: Source
      type: string
    - jsonPath: .status.suspended
      name: Suspended
      type: string
    - jsonPath: .status.failure
      name: Failure
      type: integer
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              cron:
                type: string
              maxFailure:
                default: 4
                minimum: 2
                type: integer
              retain:
                default: 8
                maximum: 250
                minimum: 2
                type: integer
              suspend:
                default: false
                type: boolean
              vmbackup:
                properties:
                  source:
                    description: |-
                      TypedLocalObjectReference contains enough information to let you locate the
                      typed referenced object inside the same namespace.
                    properties:
                      apiGroup:
                        description: |-
                          APIGroup is the group for the resource being referenced.
                          If APIGroup is not specified, the specified Kind must be in the core API group.
                          For any other third-party types, APIGroup is required.
                        type: string
                      kind:
                        description: Kind is the type of resource being referenced
                        type: string
                      name:
                        description: Name is the name of resource being referenced
                        type: string
                    required:
                    - kind
                    - name
                    type: object
                    x-kubernetes-map-type: atomic
                  type:
                    default: backup
                    enum:
                    - backup
                    - snapshot
                    type: string
                required:
                - source
                type: object
            required:
            - cron
            - maxFailure
            - retain
            - vmbackup
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              failure:
                type: integer
              suspended:
                type: boolean
              vmbackupInfo:
                items:
                  properties:
                    error:
                      description: Error is the last error encountered during the
                        snapshot/restore
                      properties:
                        message:
                          type: string
                        time:
                          format: date-time
                          type: string
                      type: object
                    name:
                      type: string
                    readyToUse:
                      type: boolean
                    volumeBackupInfo:
                      items:
                        properties:
                          error:
                            description: Error is the last error encountered during
                              the snapshot/restore
                            properties:
                              message:
                                type: string
                              time:
                                format: date-time
                                type: string
                            type: object
                          name:
                            type: string
                          readyToUse:
                            type: boolean
                        type: object
                      type: array
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
