
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: securitygroups.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: SecurityGroup
    listKind: SecurityGroupList
    plural: securitygroups
    shortNames:
    - sg
    singular: securitygroup
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          allowIngressSpec:
            items:
              properties:
                ipProtocol:
                  enum:
                  - tcp
                  - udp
                  - icmp
                  - icmpv6
                  type: string
                ports:
                  items:
                    format: int32
                    type: integer
                  type: array
                sourceAddress:
                  type: string
              required:
              - ipProtocol
              - sourceAddress
              type: object
            type: array
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
