---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: supportbundles.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: SupportBundle
    listKind: SupportBundleList
    plural: supportbundles
    shortNames:
    - sb
    - sbs
    singular: supportbundle
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.issueURL
      name: ISSUE_URL
      type: string
    - jsonPath: .spec.description
      name: DESCRIPTION
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: AGE
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              description:
                type: string
              expiration:
                description: Number of minutes Harvester waits before deleting a support
                  bundle that has been packaged but not downloaded (either deliberately
                  or unsuccessfully) or retained.
                minimum: 0
                type: integer
              extraCollectionNamespaces:
                items:
                  type: string
                type: array
              issueURL:
                type: string
              nodeTimeout:
                description: Number of minutes Harvester allows for collection of
                  logs and configurations (Harvester) on the nodes for the support
                  bundle.
                minimum: 0
                type: integer
              timeout:
                description: |-
                  Number of minutes Harvester allows for the completion of the support bundle generation process.
                  Zero means no timeout.
                minimum: 0
                type: integer
            required:
            - description
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      type: string
                    lastUpdateTime:
                      description: The last time this condition was updated.
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        last transition
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of the condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              filename:
                type: string
              filesize:
                format: int64
                type: integer
              progress:
                type: integer
              state:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources: {}
