---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: resourcequotas.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: ResourceQuota
    listKind: ResourceQuotaList
    plural: resourcequotas
    shortNames:
    - hrq
    - hrqs
    singular: resourcequota
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.snapshotLimit.namespaceTotalSnapshotSizeQuota
      name: NAMESPACE_TOTAL_SNAPSHOT_SIZE_QUOTA
      type: string
    - jsonPath: .status.snapshotLimitStatus.namespaceTotalSnapshotSizeUsage
      name: NAMESPACE_TOTAL_SNAPSHOT_SIZE_USAGE
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              snapshotLimit:
                properties:
                  namespaceTotalSnapshotSizeQuota:
                    format: int64
                    minimum: 0
                    type: integer
                  vmTotalSnapshotSizeQuota:
                    additionalProperties:
                      format: int64
                      type: integer
                    type: object
                type: object
            type: object
          status:
            properties:
              snapshotLimitStatus:
                properties:
                  namespaceTotalSnapshotSizeUsage:
                    format: int64
                    type: integer
                  vmTotalSnapshotSizeUsage:
                    additionalProperties:
                      format: int64
                      type: integer
                    type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
