---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: virtualmachinecpumodels.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: VirtualMachineCPUModel
    listKind: VirtualMachineCPUModelList
    plural: virtualmachinecpumodels
    singular: virtualmachinecpumodel
  scope: Cluster
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            properties:
              globalModels:
                items:
                  type: string
                type: array
              models:
                additionalProperties:
                  properties:
                    migrationSafe:
                      description: |-
                        MigrationSafe indicates whether VMs with this CPU model can be safely migrated.
                        MigrationSafe is true if there are more than one ready nodes with this CPU model.
                      type: boolean
                    readyCount:
                      description: |-
                        ReadyCount indicates the number of nodes that are ready with this CPU model.
                        If ReadyCount > 1, it means there are at least two ready nodes with this CPU model.
                        If ReadyCount <= 1, migration is not possible as there is at most one ready node with this CPU model.
                      type: integer
                  required:
                  - migrationSafe
                  - readyCount
                  type: object
                type: object
              totalNodes:
                type: integer
            required:
            - globalModels
            - models
            - totalNodes
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
