
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  creationTimestamp: null
  name: addons.harvesterhci.io
spec:
  group: harvesterhci.io
  names:
    kind: Addon
    listKind: AddonList
    plural: addons
    singular: addon
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.repo
      name: HelmRepo
      type: string
    - jsonPath: .spec.chart
      name: ChartName
      type: string
    - jsonPath: .spec.enabled
      name: Enabled
      type: boolean
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              chart:
                type: string
              enabled:
                type: boolean
              repo:
                type: string
              valuesContent:
                type: string
              version:
                type: string
            required:
            - chart
            - enabled
            - repo
            - valuesContent
            - version
            type: object
          status:
            properties:
              status:
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
