# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

# -- Annotations for the Deployment
annotations: {}

# -- Annotations for the Deployment Pods
podAnnotations: {}

# -- Annotations for the Deployment Pods
podLabels: {}

# -- Pod security context (runAsUser, etc.)
podSecurityContext: {}

# -- Toggle to create ClusterRole and ClusterRoleBinding
rbac:
  create: true

serviceAccount:
  # -- Toggle to create ServiceAccount
  create: true
  # -- Service account name
  name:

image:
  # -- Image registry
  registry: docker.io
  # -- Image repo
  repository: grafana/agent-operator
  # -- Image tag
  tag: v0.25.1
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image pull secrets
  pullSecrets: []

# -- If both are set, Agent Operator will create and maintain a service for scraping kubelets
# https://grafana.com/docs/agent/latest/operator/getting-started/#monitor-kubelets
kubeletService:
  namespace: default
  serviceName: kubelet

# -- List of additional cli arguments to configure agent-operator (example: `--log.level`)
extraArgs: []

# -- Resource limits and requests config
resources: {}

# -- nodeSelector configuration
nodeSelector: {}

# -- Tolerations applied to Pods
tolerations: []

# -- Pod affinity configuration
affinity: {}
