apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{ include "harvester-journald.labels" . | indent 4}}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush             1
        Grace             5
        Daemon            Off
        Log_Level         info
        Coro_Stack_Size   24576

    [INPUT]
        Name              systemd
        Tag               journald-logs
        Path              {{ .Values.systemdLogPath }}
        {{- if .Values.stripUnderscores }}
        Strip_Underscores On
        {{- end }}

    [INPUT]
        Name              tail
        Tag               rke2
        Path              /var/lib/rancher/rke2/agent/logs/kubelet.log

    [OUTPUT]
        Name              forward
        Match             *
        Host              {{ .Values.loggingOperatorServiceHost }}
        Port              24240
        Retry_Limit       False
