apiVersion: v1
kind: ServiceAccount
metadata:
  # NB(thxCode): name cannot be customized as below:
  # name: {{ template "cdi-operator.fullname" . }}
  # because the installation strategy dump action needs this ServiceAccount.
  name: cdi-operator
  labels:
{{ include "cdi-operator.labels" . | indent 4 }}
    app.kubernetes.io/name: cdi-operator
    app.kubernetes.io/component: operator
