{{- if  .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: {{ include "release_namespace" . }}
  labels:
    {{- include "longhorn.labels" . | nindent 4 }}
    name: longhorn-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: longhorn-manager
  namespaceSelector:
    matchNames:
    - {{ include "release_namespace" . }}
  endpoints:
  - port: manager
{{- end }}