{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harvesterhci.io:vm-catalog:user
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - subresources.kubevirt.io
  resources:
  - virtualmachines/expand-vm-spec
  verbs:
  - create
  - update
- apiGroups:
  - instancetype.kubevirt.io
  resources:
  - virtualmachineclusterinstancetypes
  - virtualmachineclusterpreferences
  verbs:
  - get
  - list
  - watch
{{- end }}
