apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: rancher-vm
    app.kubernetes.io/version: master
  name: rancher-vm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rancher-vm
    app.kubernetes.io/version: master
  name: rancher-vm-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: rancher-vm
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rancher-vm
    app.kubernetes.io/version: master
  name: rancher-vm
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 8443
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: rancher-vm
    app.kubernetes.io/version: master
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: rancher-vm
    app.kubernetes.io/version: master
  name: rancher-vm
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/name: rancher-vm
      app.kubernetes.io/version: master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: server
        app.kubernetes.io/name: rancher-vm
        app.kubernetes.io/version: master
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
            weight: 1
      containers:
      - image: rancher/vm:master
        imagePullPolicy: Always
        name: vm
        ports:
        - containerPort: 8443
          name: http
          protocol: TCP
      serviceAccountName: rancher-vm
