#!/bin/bash
set -eu

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"

cd ${TOP_DIR}

source ${SCRIPTS_DIR}/lib/addon
ADDONS_PATH=${TOP_DIR}/addons
load_addon_env ${ADDONS_PATH}

MONITORING_VERSION=${RANCHER_MONITORING_CHART_VERSION}
LOGGING_VERSION=${RANCHER_LOGGING_CHART_VERSION}
echo "Harvester eventrouter image: ${HARVESTER_EVENTROUTER_IMAGE_REPOSITORY}:${HARVESTER_EVENTROUTER_IMAGE_TAG}"

source ${SCRIPTS_DIR}/version
source ${SCRIPTS_DIR}/version-rke2
source ${SCRIPTS_DIR}/version-rancher
source ${SCRIPTS_DIR}/lib/image

echo "Installer version: ${VERSION}"
echo "Harvester version: ${VERSION}"
echo "Harvester chart version: ${CHART_VERSION}"
echo "Rancher version: ${RANCHER_VERSION}"
echo "Rancher monitoring version: ${MONITORING_VERSION}"
echo "Rancher logging version: ${LOGGING_VERSION}"
echo "Kubeovn operator version: ${KUBEOVN_OPERATOR_CHART_VERSION}"
echo "The ARCH is: ${ARCH}"

mkdir -p bin

PRIME_BUILD_VALUE=${PRIME_BUILD:-}
RANCHER_PRIME_REGISTRY=
if [[ "${PRIME_BUILD_VALUE}" == "true" ]]; then
    if [[ -z "${MK_RANCHER_PRIME_REGISTRY:-}" ]]; then
        echo "MK_RANCHER_PRIME_REGISTRY is required when PRIME_BUILD=true" >&2
        exit 1
    fi

    RANCHER_PRIME_REGISTRY=$(validate_registry "${MK_RANCHER_PRIME_REGISTRY}" MK_RANCHER_PRIME_REGISTRY)
fi

LINKFLAGS="-X github.com/harvester/harvester/pkg/installer/config.RKE2Version=$RKE2_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.RancherVersion=$RANCHER_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.PrimeBuild=$PRIME_BUILD_VALUE
           -X github.com/harvester/harvester/pkg/installer/config.SystemDefaultRegistry=$RANCHER_PRIME_REGISTRY
           -X github.com/harvester/harvester/pkg/installer/version.Version=$VERSION
           -X github.com/harvester/harvester/pkg/installer/version.GitCommit=$COMMIT
           -X github.com/harvester/harvester/pkg/installer/version.HarvesterVersion=$VERSION
           -X github.com/harvester/harvester/pkg/installer/config.HarvesterChartVersion=$CHART_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.MonitoringChartVersion=$MONITORING_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.LoggingChartVersion=$LOGGING_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.KubeovnOperatorChartVersion=$KUBEOVN_OPERATOR_CHART_VERSION"

OTHER_COMPILERFLAGS=""
OTHER_LINKFLAGS=""
if [ "$(uname)" = "Linux" ]; then
    if [ -n "${REMOTE_DEBUG:-}" ]; then
        OTHER_COMPILERFLAGS="all=-N -l"
        OTHER_LINKFLAGS="-extldflags -static"
    else
        OTHER_LINKFLAGS="-extldflags -static -s"
    fi
fi


# validate the addons/ packaging contract and render template files
go run ./cmd/addon-generator -validate -addonsPath ${ADDONS_PATH}
go run ./cmd/addon-generator -generateTemplates -addonsPath ${ADDONS_PATH} -path ${TOP_DIR}/pkg/installer/config/templates

# sprint releases: pin the nvidia-driver-toolkit tag embedded in the installer
freeze_sprint_image_tags ${TOP_DIR}/pkg/installer/config/templates

CGO_ENABLED=0 go build -gcflags "${OTHER_COMPILERFLAGS}" -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/harvester-installer ./cmd/installer
