#!/bin/bash
set -eu

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"

cd ${TOP_DIR}

source ${SCRIPTS_DIR}/lib/addon
ADDONS_PATH=${TOP_DIR}/../addons
load_addon_env ${ADDONS_PATH}

MONITORING_VERSION=${RANCHER_MONITORING_CHART_VERSION}
LOGGING_VERSION=${RANCHER_LOGGING_CHART_VERSION}
echo "HARVESTER_EVENTROUTER_FULL_TAG: $HARVESTER_EVENTROUTER_FULL_TAG"

source ${SCRIPTS_DIR}/version
source ${SCRIPTS_DIR}/version-rke2
source ${SCRIPTS_DIR}/version-rancher

echo "Installer version: ${VERSION}"
echo "Harvester version: ${VERSION}"
echo "Harvester chart version: ${CHART_VERSION}"
echo "Rancher version: ${RANCHER_VERSION}"
echo "Rancher monitoring version: ${MONITORING_VERSION}"
echo "Rancher logging version: ${LOGGING_VERSION}"
echo "Kubeovn operator version: ${KUBEOVN_OPERATOR_CHART_VERSION}"
echo "The ARCH is: ${ARCH}"

mkdir -p bin

LINKFLAGS="-X github.com/harvester/harvester/pkg/installer/config.RKE2Version=$RKE2_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.RancherVersion=$RANCHER_VERSION
           -X github.com/harvester/harvester/pkg/installer/version.Version=$VERSION
           -X github.com/harvester/harvester/pkg/installer/version.GitCommit=$COMMIT
           -X github.com/harvester/harvester/pkg/installer/version.HarvesterVersion=$VERSION
           -X github.com/harvester/harvester/pkg/installer/config.HarvesterChartVersion=$CHART_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.MonitoringChartVersion=$MONITORING_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.LoggingChartVersion=$LOGGING_VERSION
           -X github.com/harvester/harvester/pkg/installer/config.KubeovnOperatorChartVersion=$KUBEOVN_OPERATOR_CHART_VERSION"

OTHER_COMPILERFLAGS=""
OTHER_LINKFLAGS=""
if [ "$(uname)" = "Linux" ]; then
    if [ -n "${REMOTE_DEBUG:-}" ]; then
        OTHER_COMPILERFLAGS="all=-N -l"
        OTHER_LINKFLAGS="-extldflags -static"
    else
        OTHER_LINKFLAGS="-extldflags -static -s"
    fi
fi


# render template files
cd ${ADDONS_PATH}
go run . -generateTemplates -path ${TOP_DIR}/pkg/installer/config/templates

cd ${TOP_DIR}

CGO_ENABLED=0 go build -gcflags "${OTHER_COMPILERFLAGS}" -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/harvester-installer ./cmd/installer


check_monitoring_logging_addon_image_matching_debug() {
  if [[ -n "${MONITORING_LOGGING_ADDON_IMAGE_VALIDATION_FUNC}" ]]; then
    # The Harvester and Addons are two separate repos.
    # The images exist on ${SCRIPTS_DIR}/images/rancher-images.txt (maintained by contributors manually)
    # are pulled and packed into ISO by the ISO builder.
    # The rancher-monitoring and rancher-logging chart images are extracted from the chart files (Addon repo) and stored in ${MONITORING_LOGGING_ADDON_IMAGE_FILE},
    #  even complex, a few images are shared by the addons and the embedded `Rancher`.
    # From time to time, some images are accidentally removed or overwritten from ${SCRIPTS_DIR}/images/rancher-images.txt.
    # For example, bump `Rancher` changes one image tag, but it was actually still used by the addons.

    # The following function ensures the images claimed by the addons are all included in the ISO builder image list, and that the versions match.
    echo "check addon chart images matching"
    # function is defined on addons/scripts/hack/check-monitoring-logging-chart-images, which is loaded by load_addon_env
    ${MONITORING_LOGGING_ADDON_IMAGE_VALIDATION_FUNC} "${MONITORING_LOGGING_ADDON_IMAGE_FILE}" "${SCRIPTS_DIR}/images/rancher-images.txt"
  else
    echo "Warning: skip check monitoring and logging addon chart images matching as the check-chart-images script or chart-images-list.txt is not found in the addon repo"
  fi
}

check_monitoring_logging_addon_image_matching_debug