#!/bin/bash
# DESC: Build the Harvester ISO
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "Start building ISO image"

HARVESTER_INSTALLER_REPO="${HARVESTER_INSTALLER_REPO:-https://github.com/harvester/harvester-installer.git}"
HARVESTER_INSTALLER_REF="${HARVESTER_INSTALLER_REF:-v1.6.1}"

echo "Installer repository: ${HARVESTER_INSTALLER_REPO}"
echo "Installer ref: ${HARVESTER_INSTALLER_REF}"

git clone --branch ${HARVESTER_INSTALLER_REF} --single-branch --depth 1 ${HARVESTER_INSTALLER_REPO} ../harvester-installer

cd ../harvester-installer/scripts

./ci

cd ..
HARVESTER_DIR=../harvester

mkdir -p ${HARVESTER_DIR}/dist/artifacts
cp dist/artifacts/* ${HARVESTER_DIR}/dist/artifacts
cp -r dist/harvester-cluster-repo  ${HARVESTER_DIR}/dist

