#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "Replace the Chart version"
sed -i -e "s/0.0.0-dev/${CHART_VERSION}/g" deploy/charts/harvester/Chart.yaml
sed -i -e "s/v0.0.0-dev/${APP_VERSION}/g" deploy/charts/harvester/Chart.yaml
sed -i -e "s/%IMAGE_TAG%/${IMAGE_TAG}/g" deploy/charts/harvester/values.yaml

sed -i -e "s/0.0.0-dev/${CHART_VERSION}/g" deploy/charts/harvester-crd/Chart.yaml
sed -i -e "s/v0.0.0-dev/${APP_VERSION}/g" deploy/charts/harvester-crd/Chart.yaml

echo "Start building ISO image"

HARVESTER_INSTALLER_VERSION=master

git clone --branch ${HARVESTER_INSTALLER_VERSION} --single-branch --depth 1 https://github.com/harvester/harvester-installer.git ../harvester-installer

cd ../harvester-installer/scripts

./ci

cd ..
HARVESTER_DIR=../harvester

mkdir -p ${HARVESTER_DIR}/dist/artifacts
cp dist/artifacts/* ${HARVESTER_DIR}/dist/artifacts

