#!/bin/bash
set -e

function mirror_harvester_dependencies() {
  pushd "harvester" >/dev/null 2>&1 || exit 1

  if [[ -n "$(command -v "helm")" ]]; then
    # mirror minio
    helm repo add minio-std https://helm.min.io/
    helm pull minio-std/minio
    tar -xvzf minio-*.tgz -C charts
    rm minio-*.tgz
  else
    echo "failed to mirror the dependencies of 'harvester' chart as the 'helm' is not found"
  fi

  popd
}

ROOR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

pushd "${ROOR_DIR}/deploy/charts" >/dev/null 2>&1 || exit 1

mirror_harvester_dependencies

popd
