#!/bin/bash
# DESC: package addons yamls
set -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
UPGRADE_DIR="${TOP_DIR}/package/upgrade"
ADDONS_DIR="${TOP_DIR}/../addons"
HARVESTER_ADDONS_VERSION="v1.6.1"


## package addon yamls
git clone --branch ${HARVESTER_ADDONS_VERSION} --single-branch --depth 1 https://github.com/harvester/addons.git ${ADDONS_DIR}
cd ${ADDONS_DIR}
mkdir -p ${TOP_DIR}/package/upgrade/addons
go run .  -generateAddons -path ${TOP_DIR}/package/upgrade/addons/
ls -l ${TOP_DIR}/package/upgrade/addons/
cd ${TOP_DIR}
##
