#!/bin/bash
# DESC: Build, tag and push the harvester-upgrade image
set -e

TOP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"
SCRIPTS_DIR="${TOP_DIR}/scripts"
UPGRADE_DIR="${TOP_DIR}/package/upgrade"
ADDONS_DIR="${TOP_DIR}/../addons"
HARVESTER_ADDONS_VERSION="main"


${SCRIPTS_DIR}/generate-addons

source $SCRIPTS_DIR/version

cd $UPGRADE_DIR



IMAGE=${REPO}/harvester-upgrade:${TAG}
DOCKERFILE=Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

cp ../../bin/upgrade-helper .

BUILD_ARGS="--build-arg ARCH=${ARCH}"
if [ -n "${HARVESTER_INSTALLER_REF}" ]; then
    BUILD_ARGS="${BUILD_ARGS} --build-arg HARVESTER_INSTALLER_REF=${HARVESTER_INSTALLER_REF}"
fi
docker build -f ${DOCKERFILE} ${BUILD_ARGS} -t ${IMAGE} .
echo Built ${IMAGE}

IMAGE_PUSH=${REPO}/harvester-upgrade:${IMAGE_PUSH_TAG}
docker tag "${IMAGE}" "${IMAGE_PUSH}"
echo Tagged "${IMAGE_PUSH}"

DOCKER_CONFIG="../../.docker"
if [[ -n ${PUSH} ]];then
  docker --config=${DOCKER_CONFIG} push "${IMAGE_PUSH}"
  echo Pushed "${IMAGE_PUSH}"
fi
