#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/harvester-webhook dist/artifacts/harvester-webhook${SUFFIX}

cd $(dirname $0)/package

IMAGE=${REPO}/harvester-webhook:${TAG}
DOCKERFILE=Dockerfile.webhook
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

cp ../bin/harvester-webhook .

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

IMAGE_PUSH=${REPO}/harvester-webhook:${IMAGE_PUSH_TAG}
docker tag "${IMAGE}" "${IMAGE_PUSH}"
echo Tagged "${IMAGE_PUSH}"

DOCKER_CONFIG="../.docker"
if [[ -n ${PUSH} ]];then
  docker --config=${DOCKER_CONFIG} push "${IMAGE_PUSH}"
  echo Pushed "${IMAGE_PUSH}"
fi