#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

IMAGE=${REPO}/harvester-bundle:${TAG}
DOCKERFILE=Dockerfile.bundle
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
