#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/rancher-vm dist/artifacts/rancher-vm${SUFFIX}

cd $(dirname $0)/package

IMAGE=${REPO}/vm:${TAG}
DOCKERFILE=Dockerfile
if [ -e ${DOCKERFILE}.${ARCH} ]; then
    DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

cp ../bin/rancher-vm .

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
