#!/bin/bash
# DESC: Runs the integration tests
set -e

source $(dirname $0)/version

# The root of the harvester directory
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

export PRELOADING_IMAGES="rancher/harvester-webhook:${TAG}"
export WEBHOOK_IMAGE_NAME="rancher/harvester-webhook:${TAG}"

echo "Running integration tests"
CGO_ENABLED=0 ginkgo -r -v -trace -tags=test \
	      -fail-fast -slow-spec-threshold=2m -timeout=30m  "${ROOT_DIR}/tests/integration/..."
