#!/bin/bash
# DESC: Runs following validations: go fmt, go vet, and golangci-lint
set -e

cd $(dirname $0)/..

echo "Running validation"

if [[ -z "$(command -v golangci-lint)" ]]; then
	echo "no golangci-lint available, using go fmt/vet instead"
	echo "Running: go fmt"
	go fmt ./...
	echo "Running: go vet"
	go vet -tags=test ./...
	exit
fi

# lint takes time to finish, add a timeout param to increase the duration
date
echo "Running: golangci-lint run with --timeout=10m"
golangci-lint run --timeout=10m
date
