#!/bin/bash
# DESC: Validates the CI environment by running a dirty check on the Git repository.
set -e

cd $(dirname $0)/..

echo "Running dirty check"

go generate

source ./scripts/version

if [ -n "$DIRTY" ]; then
    echo Git is dirty
    git status
    git diff
    exit 1
fi
