# system-upgrade-controller(https://github.com/rancher/system-upgrade-controller) watches secret and node change.
# If there is a new node, system-upgrade-controller creates a job on the node to change CA certificates.
# If additional-ca is changed, system-upgrade-controller creates a job on each node to change CA certificates.
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: sync-additional-ca
  namespace: cattle-system
spec:
  concurrency: 1
  nodeSelector:
    matchLabels:
      harvesterhci.io/managed: "true"
  serviceAccountName: system-upgrade-controller
  secrets:
    - name: harvester-additional-ca
      path: /ca
  version: v1.0.2
  upgrade:
    image: {{ .Values.generalJob.image.repository }}:{{ .Values.generalJob.image.tag }}
    command: ["/bin/sh", "-c"]
    args:
      - cp /ca/additional-ca.pem /host/etc/pki/trust/anchors;
      - chroot /host update-ca-certificates
