apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "harvester.fullname" . }}
  # because we can easily confirm this resource directly.
  name: harvester
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # NB(thxCode): we give the whole permission of cluster admin to harvester.
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: harvester
    namespace: {{ .Release.Namespace }}
