---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester
{{- if .Values.replicas }}
  # The annotation does not support 0 replicas, which is used in integration tests.
  annotations:
    management.cattle.io/scale-available: "{{ .Values.replicas }}"
{{- end }}
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
spec:
  selector:
    matchLabels:
{{ include "harvester.immutableLabels" . | indent 6 }}
      app.kubernetes.io/name: harvester
      app.kubernetes.io/component: apiserver
{{- if not .Values.replicas }}
  # Use this field instead of the scale-available annotation when it is 0 replicas.
  replicas: {{ .Values.replicas }}
{{- end }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
{{ include "harvester.labels" . | indent 8 }}
        app.kubernetes.io/name: harvester
        app.kubernetes.io/component: apiserver
      annotations:
        container.apparmor.security.beta.kubernetes.io/apiserver: unconfined
    spec:
      serviceAccountName: harvester
      affinity:
{{ include "harvester.apiAffinity" (dict "root" . "component" "apiserver") | indent 8 }}
      containers:
        - name: apiserver
          image: {{ .Values.containers.apiserver.image.repository }}:{{ .Values.containers.apiserver.image.tag }}
          imagePullPolicy: {{ .Values.containers.apiserver.image.imagePullPolicy }}
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
{{- if .Values.containers.apiserver.command }}
          command:
{{ toYaml .Values.containers.apiserver.command | indent 12 }}
{{- end }}
{{- if .Values.containers.apiserver.args }}
          args:
{{ toYaml .Values.containers.apiserver.args | indent 12 }}
{{- end }}
          env:
            - name: HARVESTER_SERVER_HTTPS_PORT
              value: {{ .Values.service.harvester.httpsPort | quote }}
            - name: HARVESTER_DEBUG
              value: {{ .Values.containers.apiserver.debug | quote }}
            - name: HARVESTER_SERVER_HTTP_PORT
              value: {{ .Values.service.harvester.httpPort | quote }}
{{- if .Values.containers.apiserver.hciMode }}
            - name: HCI_MODE
              value: "true"
{{- end }}
{{- if .Values.rancherEmbedded }}
            - name: RANCHER_EMBEDDED
              value: "true"
{{- end }}
{{- if .Values.rancherURL }}
            - name: RANCHER_SERVER_URL
              value: {{  .Values.rancherURL }}
{{- end }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- if .Values.containers.apiserver.env }}
{{ toYaml .Values.containers.apiserver.env | indent 12 }}
{{- end }}
          ports:
{{- if gt (.Values.service.harvester.httpsPort | int) 0 }}
            - containerPort: {{ .Values.service.harvester.httpsPort }}
              name: https
              protocol: TCP
{{- end }}
{{- if gt (.Values.service.harvester.httpPort | int) 0 }}
            - containerPort: {{ .Values.service.harvester.httpPort }}
              name: http
              protocol: TCP
{{- end }}
            - containerPort: {{ .Values.service.harvester.profile }}
              name: profile
              protocol: TCP
{{- if .Values.containers.apiserver.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.containers.apiserver.livenessProbe | indent 12 }}
{{- end }}
{{- if .Values.containers.apiserver.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.containers.apiserver.readinessProbe | indent 12 }}
{{- end }}
{{- if .Values.containers.apiserver.resources }}
          resources:
{{ toYaml .Values.containers.apiserver.resources | indent 12 }}
{{- end }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-webhook
  annotations:
    management.cattle.io/scale-available: "{{ .Values.webhook.replicas }}"
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester-webhook
    app.kubernetes.io/component: webhook-server
spec:
  selector:
    matchLabels:
{{ include "harvester.immutableLabels" . | indent 6 }}
      app.kubernetes.io/name: harvester
      app.kubernetes.io/component: webhook-server
  template:
    metadata:
      labels:
{{ include "harvester.labels" . | indent 8 }}
        app.kubernetes.io/name: harvester
        app.kubernetes.io/component: webhook-server
      annotations:
        container.apparmor.security.beta.kubernetes.io/harvester-webhook: unconfined
    spec:
      serviceAccountName: harvester
      affinity:
{{ include "harvester.apiAffinity" (dict "root" . "component" "webhook-server") | indent 8 }}
      containers:
      - env:
        - name: HARVESTER_WEBHOOK_SERVER_HTTPS_PORT
          value: {{ .Values.webhook.httpsPort | quote }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HARVESTER_DEBUG
          value: {{ .Values.webhook.debug | quote }}
        - name: HARVESTER_CONTROLLER_USER_NAME
          value: {{ .Values.webhook.controllerUser | default (print "system:serviceaccount:" .Release.Namespace ":harvester")  | quote }}
        image: {{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag }}
        name: harvester-webhook
        args: []
        imagePullPolicy: {{ .Values.webhook.image.imagePullPolicy }}
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        ports:
        - name: https
          containerPort: {{ .Values.webhook.httpsPort }}
