apiVersion: apps/v1
kind: Deployment
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "harvester.fullname" . }}
  # because we can easily confirm this resource from the corresponding namespace.
  name: harvester
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
spec:
  selector:
    matchLabels:
{{ include "harvester.immutableLabels" . | indent 6 }}
      app.kubernetes.io/name: harvester
      app.kubernetes.io/component: apiserver
  replicas: {{ .Values.replicas }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
{{ include "harvester.labels" . | indent 8 }}
        app.kubernetes.io/name: harvester
        app.kubernetes.io/component: apiserver
    spec:
      serviceAccountName: harvester
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - harvester
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - apiserver
                  - key: app.kubernetes.io/version
                    operator: In
                    values:
                      - {{ .Chart.AppVersion }}
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: apiserver
          image: {{ .Values.containers.apiserver.image.repository }}:{{ .Values.containers.apiserver.image.tag }}
          imagePullPolicy: {{ .Values.containers.apiserver.image.imagePullPolicy }}
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
{{- if .Values.containers.apiserver.command }}
          command:
{{ toYaml .Values.containers.apiserver.command | indent 12 }}
{{- end }}
{{- if .Values.containers.apiserver.args }}
          args:
{{ toYaml .Values.containers.apiserver.args | indent 12 }}
{{- end }}
          env:
            - name: HARVESTER_AUTHENTICATION_MODE
              value: {{ .Values.containers.apiserver.authMode | quote }}
{{- if .Values.containers.apiserver.hciMode }}
            - name: HCI_MODE
              value: "true"
{{- end }}
            - name: HARVESTER_SERVER_HTTPS_PORT
              value: {{ .Values.service.harvester.httpsPort | quote }}
            - name: HARVESTER_DEBUG
              value: {{ .Values.containers.apiserver.debug | quote }}
            - name: HARVESTER_SERVER_HTTP_PORT
              value: {{ .Values.service.harvester.httpPort | quote }}
            {{- if .Values.rancherEmbedded }}
            - name: RANCHER_EMBEDDED
              value: "true"
            {{- end }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{- if .Values.containers.apiserver.env }}
{{ toYaml .Values.containers.apiserver.env | indent 12 }}
{{- end }}
          ports:
            - containerPort: {{ .Values.service.harvester.httpsPort }}
              name: https
              protocol: TCP
{{- if gt (.Values.service.harvester.httpPort | int) 0 }}
            - containerPort: {{ .Values.service.harvester.httpPort }}
              name: http
              protocol: TCP
{{- end }}
            - containerPort: {{ .Values.service.harvester.profile }}
              name: profile
              protocol: TCP
{{- if .Values.containers.apiserver.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.containers.apiserver.livenessProbe | indent 12 }}
{{- end }}
{{- if .Values.containers.apiserver.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.containers.apiserver.readinessProbe | indent 12 }}
{{- end }}
{{- if .Values.containers.apiserver.resources }}
          resources:
{{ toYaml .Values.containers.apiserver.resources | indent 12 }}
{{- end }}
{{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
