{{- if .Values.longhorn.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: harvester-longhorn
  annotations:
    harvesterhci.io/is-reserved-storageclass: "true"
{{ include "harvester.annotations.defaultstorageclass" . | indent 4 }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "{{ .Values.storageClass.reclaimPolicy }}"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "{{ .Values.storageClass.replicaCount }}"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
  migratable: "true"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vmstate-persistence
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "{{ .Values.storageClass.reclaimPolicy }}"
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "{{ .Values.storageClass.replicaCount }}"
  staleReplicaTimeout: "30"
{{- end -}}
