# This configmap is a hook to add the migratable param to the longhorn storage class
{{ if .Values.longhorn.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-storageclass
  namespace: {{ .Values.longhorn.namespaceOverride }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels: {{- include "longhorn.labels" . | nindent 4 }}
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
      annotations:
        storageclass.kubernetes.io/is-default-class: {{ .Values.longhorn.persistence.defaultClass | quote }}
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: "{{ .Values.longhorn.persistence.reclaimPolicy }}"
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "{{ .Values.longhorn.persistence.defaultClassReplicaCount }}"
      staleReplicaTimeout: "30"
      fromBackup: ""
      baseImage: ""
      migratable: "true"
{{- end -}}
