---
apiVersion: v1
kind: Service
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "harvester.fullname" . }}
  # because we can easily confirm this resource from the corresponding namespace.
  name: harvester
  annotations:
{{- if and (eq .Values.service.harvester.type "LoadBalancer") (eq .Values.service.harvester.vipMode "DHCP") }}
{{- if and .Values.service.harvester.vip .Values.service.harvester.vipHwAddr }}
    kube-vip.io/requestedIP: {{ .Values.service.harvester.vip }}
    kube-vip.io/hwaddr: {{ .Values.service.harvester.vipHwAddr }}
{{- end }}
{{- end }}
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
{{- if .Values.service.harvester.asClusterService }}
    kubernetes.io/cluster-service: "true"
{{- end }}
spec:
  sessionAffinity: {{ .Values.service.harvester.sessionAffinity }}
  type: {{ .Values.service.harvester.type }}
  selector:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
{{- if and (eq .Values.service.harvester.type "LoadBalancer") (eq .Values.service.harvester.vipMode "DHCP") }}
  loadBalancerIP: "0.0.0.0"
{{- else}}
  loadBalancerIP: {{ .Values.service.harvester.loadBalancerIP }}
{{- end }}
  ports:
{{- if gt (.Values.service.harvester.httpsPort | int) 0 }}
    - name: https
      port: {{ .Values.service.harvester.httpsPort }}
{{- if and (eq .Values.service.harvester.type "NodePort") (gt (.Values.service.harvester.httpsNodePort | int) 0) }}
      nodePort: {{ .Values.service.harvester.httpsNodePort }}
{{- end }}
      targetPort: https
{{- end }}
{{- if gt (.Values.service.harvester.httpPort | int) 0 }}
    - name: http
      port: {{ .Values.service.harvester.httpPort }}
{{- if and (eq .Values.service.harvester.type "NodePort") (gt (.Values.service.harvester.httpNodePort | int) 0) }}
      nodePort: {{ .Values.service.harvester.httpNodePort }}
{{- end }}
      targetPort: http
{{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: harvester-webhook
spec:
  ports:
  - name: https
    port: 443
    targetPort: {{ .Values.webhook.httpsPort }}
    protocol: TCP
  selector:
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: webhook-server
