apiVersion: v1
kind: Service
metadata:
  # NB(thxCode): name should not be customized as below:
  # name: {{ template "harvester.fullname" . }}
  # because we can easily confirm this resource from the corresponding namespace.
  name: harvester
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
spec:
  type: LoadBalancer
  selector:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
  ports:
    - name: https
      port: 8443
      targetPort: https
    - name: http
      port: 8080
      targetPort: http
