apiVersion: v1
kind: ServiceAccount
metadata:
  # NB(thxCode): name cannot be customized as below:
  # name: {{ template "harvester.fullname" . }}
  # because we can easily confirm this resource from the corresponding namespace.
  name: harvester
  labels:
{{ include "harvester.labels" . | indent 4 }}
    app.kubernetes.io/name: harvester
    app.kubernetes.io/component: apiserver
