name: Add-To-Projects
on:
  issues:
    types: [opened]

jobs:
  community:
    runs-on: ubuntu-latest
    steps:
    - name: Is Harvester Member
      id: is-harvester-member
      continue-on-error: true
      uses: tspascoal/get-user-teams-membership@v3
      with:
        username: ${{ github.event.issue.user.login }}
        organization: harvester
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    - name: Get Issue
      if: steps.is-harvester-member.outcome == 'success'
      uses: octokit/request-action@v2.x
      id: issue
      with:
        route: GET /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    - name: Add Issue to Community Sprint Project
      id: add-project
      if: |
        steps.is-harvester-member.outcome == 'success' &&
        fromJSON(steps.is-harvester-member.outputs.teams)[0] == null
      uses: actions/add-to-project@v1.0.2
      with:
        project-url: https://github.com/orgs/harvester/projects/10
        github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

    - name: Update Item To New
      if: |
        steps.is-harvester-member.outcome == 'success' &&
        fromJSON(steps.is-harvester-member.outputs.teams)[0] == null &&
        steps.add-project.outputs.itemId != ''
      uses: titoportas/update-project-fields@v0.1.0
      with:
        project-url: https://github.com/orgs/harvester/projects/10
        github-token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        item-id: ${{ steps.add-project.outputs.itemId }}
        field-keys: Status,Sprint
        field-values: "New,[0]"

