name: "[Issue Management] Close Issue"

# Extract full version and major.minor version
# Label "backport-needed/1.4.3" → searches for "[backport v1.4]"
# Label "backport-needed/1.5.1" → searches for "[backport v1.5]"
# Label "backport-needed/1.4" → searches for "[backport v1.4]"
# Label "backport-needed/1.5" → searches for "[backport v1.5]"
#
# Example:
# [DOC] Harvester UI extension upgrade with "backport-needed/1.5.1"
# [backport v1.5] [DOC] Harvester UI extension upgrade

on:
  issues:
    types: [ unlabeled ]
jobs:
  backport:
    runs-on: ubuntu-latest
    if: contains(github.event.label.name, 'backport-needed/')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Get Backport Version
      run: |
        FULL_VERSION=$(echo "${{ github.event.label.name }}" | cut -d'/' -f2)
        MAJOR_MINOR_VERSION=$(echo "$FULL_VERSION" | cut -d'.' -f1,2)
        echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
        echo "MAJOR_MINOR_VERSION=$MAJOR_MINOR_VERSION" >> $GITHUB_ENV
        
    - name: Find and Close Backport Issue
      run: |
        # Search for backport issues with matching title using major.minor version
        BACKPORT_ISSUE=$(gh issue list --search "[backport v${{ env.MAJOR_MINOR_VERSION }}] ${{ github.event.issue.title }}" --json number --jq '.[0].number')
        
        if [ -n "$BACKPORT_ISSUE" ]; then
          echo "Closing backport issue #$BACKPORT_ISSUE for version ${{ env.MAJOR_MINOR_VERSION }}"
          gh issue close $BACKPORT_ISSUE
        else
          echo "No matching backport issue found for version ${{ env.MAJOR_MINOR_VERSION }}"
        fi
      env:
        GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}