name: "Issue Management Backport PR Collect Data"

on:
  pull_request:
    types: [opened]
    branches:
      - master
      - "v*"

env:
  REPO_NAME: harvester/harvester

jobs:
  check-backport:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: read
    steps:

    - name: Check if PR is a backport
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        echo "PR Title: $TITLE"

        if [[ "${{ contains(github.event.pull_request.title, 'backport #') }}" == "true" ]]; then
          echo "BACKPORT=true" >> $GITHUB_ENV
        else
          echo "BACKPORT=false" >> $GITHUB_ENV
        fi

    - name: Extract backport branch and issue number
      if: env.BACKPORT == 'true'
      env:
        BASE_REF: ${{ github.event.pull_request.base.ref }}
        BODY: ${{ github.event.pull_request.body }}
      run: |
        # Extract branch from the target branch of the PR
        BRANCH="$BASE_REF"
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

        # Extract issue numbers from PR body (support both formats)
        ISSUE_NUMBERS=$(echo "$BODY" | grep -oE "${REPO_NAME}#([0-9]+)" | cut -d'#' -f2)
        ISSUE_NUMBERS_URL=$(echo "$BODY" | grep -oE "https://github.com/${REPO_NAME}/issues/[0-9]+" | awk -F'/' '{print $NF}')
        ISSUE_NUMBERS_SIMPLE=$(echo "$BODY" | grep -oE "#[0-9]+" | cut -c2-)
        ALL_ISSUES=$(echo -e "$ISSUE_NUMBERS\n$ISSUE_NUMBERS_URL\n$ISSUE_NUMBERS_SIMPLE" | grep -E '^[0-9]+$' | sort -u)
        
        echo "ISSUE_NUMBERS: $ISSUE_NUMBERS"
        echo "ISSUE_NUMBERS_URL: $ISSUE_NUMBERS_URL"
        echo "ISSUE_NUMBERS_SIMPLE: $ISSUE_NUMBERS_SIMPLE"
        echo "ALL_ISSUES: $ALL_ISSUES"

        ORIGINAL_ISSUE_NUMBER=$(echo $ALL_ISSUES | xargs) # trim
        echo "ORIGINAL_ISSUE_NUMBER=$ORIGINAL_ISSUE_NUMBER" >> $GITHUB_ENV

    - name: Save PR data to artifact
      run: |
        {
          echo "BACKPORT=${{ env.BACKPORT }}"
          echo "BRANCH=${{ env.BRANCH }}"
          echo "ORIGINAL_ISSUE_NUMBER=${{ env.ORIGINAL_ISSUE_NUMBER }}"
          echo "HTML_URL=${{ github.event.pull_request.html_url }}"
          echo "PR_NUMBER=${{ github.event.pull_request.number }}"
        } > pr-data.env

    - name: Upload PR data artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: pr-data
        path: pr-data.env
