name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@eb932558ad942cccfd8211cf535f17ff183a9f74 #v46.1.9
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
