name: Validate Prime

on:
  # uncomment when a stable branch includes prime builds
  # push:
  #   branches:
  #   - v1.*
  workflow_dispatch:

jobs:
  validate-prime:
    name: Validate Prime
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - name: Run validate prime
      run: make validate-prime
