[Unit]
After=time-sync.target
Wants=time-sync.target

[Service]
EnvironmentFile=-/etc/rancher/rke2/harvester-managed.env
ExecStartPre=/usr/sbin/harv-update-rke2-server-url server
ExecStartPost=/sbin/sysctl -w net.bridge.bridge-nf-call-iptables=0
